### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by alexander-adamenko** [alexander-adamenko/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by LegatikUA** [comment]
* steve@mac.com
* https://www.apple.com/

**Comment by alexander-adamenko** [comment]
Good job!
