### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by alexander-adamenko** [alexander-adamenko/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by LegatikUA** [comment]
#### He almost became a Buddhist monk 
As an adolescent, Jobs’ dream was to become a Buddhist monk. In 1974, a trip to India sparked in him a lifelong interest in Buddhism that stayed with him forever. 

#### He was into fish and veggies 
Steve Jobs was a pescetarian and his favourite food was fish. He also liked carrots and fruits and spent some time as a fruitarian, meaning he only ate fruits, nuts, seeds, vegetables, and grains. 

#### He was a college dropout 
Steve Jobs was a college dropout and attended Reeds College for just 18 months. He continued his education by informally auditing classes. In Reeds, the course that attracted him the most was calligraphy. He used to audit calligraphy classes, which famously went on to influence the typography and font of Apple products. 

#### His last words are still a mystery 
Steve Jobs final words were monosyllables that he repeated thrice “Oh wow. Oh wow. Oh wow”. The reason behind this utterance is still a mystery. 

#### He followed a simplistic dress code 
His signature dressing style included a black turtleneck, jeans, and sneakers. He was known for his simplicity with the turtle neck and Levis jeans. It is said that he had close to 100 Levis jeans throughout his lifetime. 

#### He met his biological sister at 27 
The famous author Mona Simpson is his biological sister, who he tracked down later in life. Her first novel, Anywhere but Here, was about her relationship with her parents, who were Steve Job’s biological parents as well. 

#### His lifestyle choices possibly resulted in the name ‘Apple’ 
A lot has been debated about how Steve Jobs decided to name the company. However it is said that being a fruitarian, he used to visit organic farms to collect fruits. On one such visit, it struck him to name his company Apple. 

#### He was once fired from Apple 
Even though he fell out of his own company, he took it as a blessing in disguise and later in 1997 joined back as the CEO. He later said that the feeling was very liberating and it was the most creative period of his life. 

#### He was a tough boss 
He followed strict rules and principles. He believed in being strict to follow that. 

#### He has a dedicated team to study emotions 
Jobs has a dedicated team to study the excitement and emotion behind opening a box and finding the products inside. This emotion is very common with Apple products today. 

#### He patented all his inventions 
Steve Jobs had close to 300 patents under his name. The glass staircase at the Apple store is one such patented attraction that pulls passers-by into the store.

**Comment by alexander-adamenko** [comment]
Good job!
